### ISSUE TITLE
Powershell / Windows support

### ISSUE THREAD

**Issue by seahckr** [jepsen-io/jepsen#175]
I am looking to replace the SSH infrastructure with Powershell / ps remoting to be able to run natively on Windows. Just wanted to check if there's any existing effort already in this direction, or any interest in the community for this?

I have some helper functions working, like control\on & control\on-many, but working through Control.clj,

```
(defn exec*
  "Like exec, but does not escape."
  [& commands]
  (->> commands
       (str/join " ")
       (array-map :cmd)
       wrap-cd
       wrap-sudo
       wrap-trace
       ssh*
       throw-on-nonzero-exit
       just-stdout))
```

This assumes that the right ssh session is already dynamically bound in the context of that thread.. Is this idiomatic clojure, or can we do something better? Thank you @aphyr !

**Comment by aphyr** [comment]
Oh gosh, I'm not sure. You'll probably need *some* kind of polymorphism here, but I'm not sure what concepts map well between SSH and Powershell. It might be worth implementing a standalone library instead of hacking on top of control.clj; I'm not sure how much, if any, of the control code makes any sense on Windows.On Apr 24, 2017 4:02 PM, deepakn <notifications@github.com> wrote:I am looking to replace the SSH infrastructure with Powershell / ps remoting to be able to run natively on Windows. Just wanted to check if there's any existing effort already in this direction, or any interest in the community for this?
I have some helper functions working, like control\on & control\on-many, but working through Control.clj,
(defn exec*
  "Like exec, but does not escape."
  [& commands]
  (->> commands
       (str/join " ")
       (array-map :cmd)
       wrap-cd
       wrap-sudo
       wrap-trace
       ssh*
       throw-on-nonzero-exit
       just-stdout))

This assumes that the right ssh session is already dynamically bound in the context of that thread.. Is this a idiomatic clojure, or can we do something better?

**Comment by seahckr** [comment]
Thanks for the response! Would you be willing to review a PR on my in-progress stuff? I am very interested in your thoughts on the approach.

**Comment by aphyr** [comment]
No promises--I'm traveling for like the next month--but I'll give you what I canOn Apr 27, 2017 08:45, deepakn <notifications@github.com> wrote:Thanks for the response! Would you be willing to review a PR on my in-progress stuff? I am very interested in your thoughts on the approach.
