### ISSUE TITLE
question about jepsen history

### ISSUE THREAD

**Issue by UncP** [jepsen-io/jepsen#192]
how can you ensure that the sequence of operation that shows in terminal is the actual sequence that is applied to distributed system that we are testing?

![1](https://user-images.githubusercontent.com/16263931/29022569-81a42edc-7b9c-11e7-8cda-2be930c43b4b.png)

**Comment by aphyr** [comment]
I talk about this a bit in Jepsen talks and early blog posts, but to give a fuller account:

Since both Jepsen and the system being tested are distributed, there is no definite sequence of events in either. Jepsen histories are only a *partial* order, and that order's correctness is enforced by the conjunction of three things:

1. Appends to the Jepsen history are linearizable
2. Invocations are journaled to the history *before* being applied to the system
3. Completions are journaled to the history *after* being applied to the system

From these three things, and the definition of linearizability, we can derive that the partial order of operations in the distributed system must be compatible with Jepsen's history order, although the converse is not true. This is one of the reasons why Jepsen is *sound* but not *complete*: we can prove the existence of bugs, but when anomalies are present, it's possible to miss them.

**Comment by UncP** [comment]
> Appends to the Jepsen history are linearizable

what does this mean?

**Comment by aphyr** [comment]
Could you be more specific? Are you confused about linearizability, the Jepsen history, what an append means...?

**Comment by UncP** [comment]
why is the append linearizable? what does *linearizable* here mean?

**Comment by aphyr** [comment]
Appends are linearizable because of your CPU's implementation, the semantics of the computer's instruction set, the implementation of the JVM, the Java Memory model, your Java Runtime's implementation of AtomicReference, and Clojure's use of AtomicReference. Linearizability is a correctness property for concurrent systems which, informally, means operations appear to occur atomically at some point between their invocation and completion times; for a full account see https://cs.brown.edu/~mph/HerlihyW90/p463-herlihy.pdf.

Google may be helpful here.

**Comment by UncP** [comment]
thanks, i got it.
