### ISSUE TITLE
how to slove elasticseach 5.x test?

### ISSUE THREAD

**Issue by jinhang** [jepsen-io/jepsen#201]
in https://github.com/jepsen-io/jepsen/tree/master/elasticsearch, how to use Jepsen to test my elasticseach  cluster？

**Comment by aphyr** [comment]
Jepsen runs it's own elasticsearch cluster; you probably don't want to point it at a production cluster, since it's going to destroy all the data in the cluster on each run.On Oct 11, 2017 06:30, keehang <notifications@github.com> wrote:in https://github.com/jepsen-io/jepsen/tree/master/elasticsearch, how to use Jepsen to test my elasticseach  cluster？
