### ISSUE TITLE
ssh: Could not resolve hostname n1: Name or service not known

### ISSUE THREAD

**Issue by bharambetejas** [jepsen-io/jepsen#306]
I am using the aws jepsen. I get the error when i run 'lein run test'. in test scaffolding.

<img width="1196" alt="screen shot 2019-01-31 at 9 06 58 pm" src="https://user-images.githubusercontent.com/17508216/52098226-2bb63c80-259c-11e9-90e9-b6a83b4a9dbc.png">

When i do ssh n1 i get the error.
Is the aws jepen instance just a control node and i have to create 5 db nodes and then map them?
Also i couldn't find the 'nodes' directory.

**Comment by aphyr** [comment]
Good morning @bharambetejas! If you started a single Jepsen instance than yes, this is just a control node, and it's up to you to run more if you'd like DB nodes. If you'd like to have a full cluster set up out of the box, choose the AWS Marketplace "5+1 node cluster" option.

If you're running the 5+1 node cluster (e.g. you went through the CloudFormation setup process), you've already got 5 DB nodes available. Your node names will be available in ~/nodes, which is a file, not a directory. Since you said you didn't see that, I'm guessing you're just running a single node?

**Comment by aphyr** [comment]
Amazon keeps changing this interface around, so I double-checked for you: once you've subscribed to Jepsen on AWS, go to "configuration" and choose "CloudFormation", like so:

![screenshot from 2019-02-01 07-44-56](https://user-images.githubusercontent.com/3748/52123901-787a3180-25f5-11e9-9e36-8dca260e4ac5.png)

**Comment by bharambetejas** [comment]
Thank You very much @aphyr. It worked

**Comment by aphyr** [comment]
Glad to hear it. :)
