### ISSUE TITLE
Is there any ways to run jepsen tests on the same machine but on different ports

### ISSUE THREAD

**Issue by CalvinNeo** [jepsen-io/jepsen#319]
Issue https://github.com/jepsen-io/jepsen/issues/293 says jepsen supports physical machines, VMs, or containers.

I am wondering if there are some ways that I run n1 to n5 in the same machine but with different ports, since it will be easier for me to configure and test.

**Comment by aphyr** [comment]
Technically yes, but large parts of Jepsen are built with the assumption that each node is an independent OS; you may find it takes more work to write custom code for things like DB setup and introducing faults than to set up containers or VMs in the first place. If you're planning to run an existing test, chances are it was designed with independent nodes in mind.On Feb 20, 2019 13:00, Calvin Neo <notifications@github.com> wrote:Issue #293 says jepsen supports physical machines, VMs, or containers.
I am wondering if there are some ways that I run n1 to n5 in the same machine but with different ports, since it will be easier for me to configure and test.
