### ISSUE TITLE
Control functions don't work in dummy ssh mode?

### ISSUE THREAD

**Issue by DeCarabas** [jepsen-io/jepsen#406]
I'm trying to put together a Jepsen test for an internal database, following along with the tutorial. Alas, in my environment SSH isn't really working properly, so I need to run in dummy mode. I would have thought that all the control functions would continue to run, just outside of an SSH session, but it appears that is not the case. Instead, I get an error like: "No implementation of method: :connected? of protocol: #'clj-ssh.ssh.protocols/Session found for class: clojure.lang.PersistentVector". 

Is this expected? Should it be made to work?

My test, such as it is, is @ https://gist.github.com/DeCarabas/489da7b662b125666ef162152f8d3ec8, and the full exception is below.

```
INFO [2019-08-22 19:31:55,981] jepsen test runner - jepsen.db :caught #error {
 :cause No implementation of method: :connected? of protocol: #'clj-ssh.ssh.protocols/Session found for class: clojure.lang.PersistentVector
 :via
 [{:type java.lang.IllegalArgumentException
   :message No implementation of method: :connected? of protocol: #'clj-ssh.ssh.protocols/Session found for class: clojure.lang.PersistentV
ector
   :at [clojure.core$_cache_protocol_fn invokeStatic core_deftype.clj 583]}]
 :trace
 [[clojure.core$_cache_protocol_fn invokeStatic core_deftype.clj 583]
  [clojure.core$_cache_protocol_fn invoke core_deftype.clj 575]
  [clj_ssh.ssh.protocols$fn__2424$G__2404__2429 invoke protocols.clj 4]
  [clj_ssh.ssh$connected_QMARK_ invokeStatic ssh.clj 419]
  [clj_ssh.ssh$connected_QMARK_ invoke ssh.clj 416]
  [clj_ssh.ssh$ssh invokeStatic ssh.clj 718]
  [clj_ssh.ssh$ssh invoke ssh.clj 699]
  [jepsen.control$ssh_STAR_$fn__2839 invoke control.clj 148]
  [jepsen.control$ssh_STAR_ invokeStatic control.clj 148]
  [jepsen.control$ssh_STAR_ invoke control.clj 144]
  [jepsen.control$exec_STAR_ invokeStatic control.clj 170]
  [jepsen.control$exec_STAR_ doInvoke control.clj 167]
  [clojure.lang.RestFn applyTo RestFn.java 137]
  [clojure.core$apply invokeStatic core.clj 665]
  [clojure.core$apply invoke core.clj 660]
  [jepsen.control$exec invokeStatic control.clj 186]
  [jepsen.control$exec doInvoke control.clj 180]
  [clojure.lang.RestFn invoke RestFn.java 436]
  [jepsen.control.util$cached_wget_BANG_ invokeStatic util.clj 118]
  [jepsen.control.util$cached_wget_BANG_ invoke util.clj 96]
```

**Comment by aphyr** [comment]
Jepsen.control functions work on SSH connections in order to run code on remote DB nodes. If you don't have any SSH connection... what do you think they should they do?--KyleOn Aug 22, 2019 22:41, John Doty <notifications@github.com> wrote:I'm trying to put together a Jepsen test for an internal database, following along with the tutorial. Alas, in my environment SSH isn't really working properly, so I need to run in dummy mode. I would have thought that all the control functions would continue to run, just outside of an SSH session, but it appears that is not the case. Instead, I get an error like: "No implementation of method: :connected? of protocol: #'clj-ssh.ssh.protocols/Session found for class: clojure.lang.PersistentVector".
Is this expected? Should it be made to work?
My test, such as it is, is @ https://gist.github.com/DeCarabas/489da7b662b125666ef162152f8d3ec8, and the full exception is below.
INFO [2019-08-22 19:31:55,981] jepsen test runner - jepsen.db :caught #error {
 :cause No implementation of method: :connected? of protocol: #'clj-ssh.ssh.protocols/Session found for class: clojure.lang.PersistentVector
 :via
 [{:type java.lang.IllegalArgumentException
   :message No implementation of method: :connected? of protocol: #'clj-ssh.ssh.protocols/Session found for class: clojure.lang.PersistentV
ector
   :at [clojure.core$_cache_protocol_fn invokeStatic core_deftype.clj 583]}]
 :trace
 [[clojure.core$_cache_protocol_fn invokeStatic core_deftype.clj 583]
  [clojure.core$_cache_protocol_fn invoke core_deftype.clj 575]
  [clj_ssh.ssh.protocols$fn__2424$G__2404__2429 invoke protocols.clj 4]
  [clj_ssh.ssh$connected_QMARK_ invokeStatic ssh.clj 419]
  [clj_ssh.ssh$connected_QMARK_ invoke ssh.clj 416]
  [clj_ssh.ssh$ssh invokeStatic ssh.clj 718]
  [clj_ssh.ssh$ssh invoke ssh.clj 699]
  [jepsen.control$ssh_STAR_$fn__2839 invoke control.clj 148]
  [jepsen.control$ssh_STAR_ invokeStatic control.clj 148]
  [jepsen.control$ssh_STAR_ invoke control.clj 144]
  [jepsen.control$exec_STAR_ invokeStatic control.clj 170]
  [jepsen.control$exec_STAR_ doInvoke control.clj 167]
  [clojure.lang.RestFn applyTo RestFn.java 137]
  [clojure.core$apply invokeStatic core.clj 665]
  [clojure.core$apply invoke core.clj 660]
  [jepsen.control$exec invokeStatic control.clj 186]
  [jepsen.control$exec doInvoke control.clj 180]
  [clojure.lang.RestFn invoke RestFn.java 436]
  [jepsen.control.util$cached_wget_BANG_ invokeStatic util.clj 118]
  [jepsen.control.util$cached_wget_BANG_ invoke util.clj 96]

**Comment by DeCarabas** [comment]
> what do you think they should they do?

The same thing they do remotely, just... locally? With files and so forth on the local computer?

**Comment by DeCarabas** [comment]
My justification is that it would be nice to abstract the "here's how you set up the database" part from the "here's how you talk to the remote server" part. Right now in my environment the former is easy but the latter is tricky, and the in-box SSH isn't really working for me.

**Comment by aphyr** [comment]
So... You'd have five or ten threads all racing to execute the same shell commands on the local node? Stepping on each other's files? Killing each other's processes? Taking down your network connections to localhost?On Aug 22, 2019 23:50, John Doty <notifications@github.com> wrote:
what do you think they should they do?

The same thing they do remotely, just... locally? With files and so forth on the local computer?

**Comment by DeCarabas** [comment]
> So... You'd have five or ten threads all racing to execute the same shell commands on the local node? Stepping on each other's files? Killing each other's processes? Taking down your network connections to localhost?

I would hope not. :D

At least the files and processes are relatively easy to isolate, so long as your database supports it, and mine does. The network and time nemeses won't work out of the box, obviously.

I didn't mean to be a bother: dummy mode appears to basically not be documented, but it was your suggestion when I talked to you in person about it, and I wondered if this was another case of me just holding it wrong.

**Comment by aphyr** [comment]
I mean, dummy mode works fine, it's just that using dummy mode *and* functions that need to run against remote DB nodes isn't really meaningful behavior. If you don't have access to those nodes, you shouldn't be calling functions that need to talk to them.All this is pluggable, through the OS, DB, and Nemesis protocols. You just can't use an OS that needs SSH access unless you *have* SSH access to give it. You should replace that OS (or DB, etc) with an OS that doesn't make those calls. If you just need a noop OS, you'll find noop versions of each built in to Jepsen, or you can write your own that, say, make network requests, or execute shell commands, or whatever it is you'd like to do instead.On Aug 23, 2019 00:14, John Doty <notifications@github.com> wrote:Closed #406.

**Comment by DeCarabas** [comment]
> If you just need a noop OS, you'll find noop versions of each built in to Jepsen, or you can write your own that, say, make network requests, or execute shell commands, or whatever it is you'd like to do instead.

I'm sorry, I don't understand this part. 

It doesn't look like I can use Jepsen's OS abstraction to make network requests or run shell commands: I would need to build my own. It appears that the only facilities that Jepsen provides for this are in `jepsen.control`, and those are all bound to ssh (which has to be a real ssh because it's a native SSH implementation, not a shell out to an ssh command).

In addition, some of the abstractions are integrated in a way that makes it difficult for me to replace. For example, db/LogFiles is neat but the code in the test runner assumes that it's going to be using SSH to download the files, and there's nothing I can put in the way to convince it otherwise. So somehow I need to arrange for my log files to get copied into the result store without help...

Anyway, I am not complaining: it looks like using Jepsen without SSH means re-implementing lots of functionality, is all: spawning and shutting down demon processes, running wget, copying log files around, &c. Using a dummy OS and dummy-mode on SSH at least keeps the runner itself from dying, making room for me to do my own re-implementation.

**Comment by aphyr** [comment]
Yes, this is true: all the automation tooling in Jepsen is built to use SSH, but... this is a general purpose programming language. You can pull in any JVM library you want. For shell commands, see clojure.java.shell. If you want to make HTTP requests, there's clj-http. Need to parse some JSON? Pull in Cheshire. Yes, you'll be reinventing things already in Jepsen, but that's to be expected, because you're denying Jepsen a basic, if optional, capability. It can't, like... magically figure out how to run shell commands on remote nodes some other way, haha.Some nemeses are already written with polymorphic interfaces, btw. Network partitions are pluggable, and don't have to use j.control commands. Process operations like killing or pausing processes don't have an associated protocol (yet) because nobody has needed, or found, a different way to do those things that doesn't involve SSH.On Aug 23, 2019 00:45, John Doty <notifications@github.com> wrote:
If you just need a noop OS, you'll find noop versions of each built in to Jepsen, or you can write your own that, say, make network requests, or execute shell commands, or whatever it is you'd like to do instead.

I'm sorry, I don't understand this part.
It doesn't look like I can use Jepsen's OS abstraction to make network requests or run shell commands: I would need to build my own. It appears that the only facilities that Jepsen provides for this are in jepsen.control, and those are all bound to ssh (which has to be a real ssh because it's a native SSH implementation, not a shell out to an ssh command).
In addition, some of the abstractions are integrated in a way that makes it difficult for me to replace. For example, db/LogFiles is neat but the code in the test runner assumes that it's going to be using SSH to download the files, and there's nothing I can put in the way to convince it otherwise. So somehow I need to arrange for my log files to get copied into the result store without help...
Anyway, I am not complaining: it looks like using Jepsen without SSH means re-implementing lots of functionality, is all: spawning and shutting down demon processes, running wget, copying log files around, &c. Using a dummy OS and dummy-mode on SSH at least keeps the runner itself from dying, making room for me to do my own re-implementation.
