### ISSUE TITLE
Suggestion: customization point for jepsen.control

### ISSUE THREAD

**Issue by jll63** [jepsen-io/jepsen#419]
I am working on tests for a message queue broker developed at Bloomberg. I successfully replicated the RabbitMQ test with our broker. However, since I run our nodes in Docker containers, I felt that using ssh to talk to the nodes was overkill, when `docker exec` would work just fine.

Have you considered abstracting `control`, maybe putting it behind a protocol? If I have time to work on a PR, would you look at it favorably?

Thanks for creating Jepsen!

**Comment by aphyr** [comment]
There's a protocol for jepsen.control in master right now, actually!On Oct 3, 2019 10:49, Jean-Louis Leroy <notifications@github.com> wrote:I am working on tests for a message queue broker developed at Bloomberg. I successfully replicated the RabbitMQ test with our broker. However, since I run our nodes in Docker containers, I felt that using ssh to talk to the nodes was overkill, when docker exec would work just fine.
Have you considered abstracting control, maybe putting it behind a protocol? If I have time to work on a PR, would you look at it favorably?
Thanks for creating Jepsen!

**Comment by jll63** [comment]
Oh great! I'll try it...
