### ISSUE TITLE
a `timed-out` operation cause transaction partially committed.

### ISSUE THREAD

**Issue by coocood** [jepsen-io/jepsen#428]
This happens occasionally since TiDB update the transaction model to support large transaction.
I think this issue may not only affects TiDB.

After this log, the total becomes wrong.

```
2019-12-06 23:01:26,854{GMT}	INFO	[jepsen worker 3-n4] jepsen.util: 3	:info	:transfer	{:from 3, :to 7, :amount 1}	:timed-out
```

The corresponding tidb log is the following:

```
[user=root@172.18.0.4] [schemaVersion=30] [txnStartTS=0] [current_db=test] [sql="set autocommit=0"]
[2019/12/06 23:01:26.854 +00:00] [INFO] [session.go:2041] [GENERAL_LOG] [conn=2] [user=root@172.18.0.4] [schemaVersion=30] [txnStartTS=0] [current_db=test] [sql="select balance from accounts3 FOR UPDATE"]
[2019/12/06 23:01:26.855 +00:00] [INFO] [2pc.go:1042] ["2PC clean up done"] [conn=2] [txnStartTS=413053298079170561]
[2019/12/06 23:01:26.856 +00:00] [INFO] [session.go:2041] [GENERAL_LOG] [conn=2] [user=root@172.18.0.4] [schemaVersion=30] [txnStartTS=413053298105384965] [current_db=test] [sql="select balance from accounts7 FOR UPDATE"]
[2019/12/06 23:01:26.857 +00:00] [INFO] [session.go:2041] [GENERAL_LOG] [conn=2] [user=root@172.18.0.4] [schemaVersion=30] [txnStartTS=413053298105384965] [current_db=test] [sql="update accounts3 set balance = balance - 1 where id = 0"]
[2019/12/06 23:01:26.858 +00:00] [INFO] [session.go:2041] [GENERAL_LOG] [conn=2] [user=root@172.18.0.4] [schemaVersion=30] [txnStartTS=413053298105384965] [current_db=test] [sql="set autocommit=1"]
[2019/12/06 23:01:26.862 +00:00] [INFO] [server.go:425] ["connection closed"] [conn=2]
```

The log shows that a transfer only updated one account, then executed `set autocommit=1` before close, then the unfinished transaction is committed.

Could this be a bug in `jdbc`?

One of my suspicions is:

https://github.com/clojure/java.jdbc/blob/master/src/main/clojure/clojure/java/jdbc.clj#L829

 `set autocommit = 1` is executed in the `finally` block which means if the `rollback` failed to execute, then `set autocommit = 1` is still being executed.

**Comment by aphyr** [comment]
When you say the transaction is committed, does that mean the client is explicitly committing the transaction? Or that TiDB is committing the transaction implicitly because the value of autocommit changed? It's not exactly clear to me (based on the MySQL docs) what autocommit changes are supposed to do in this situation, but I *think* I'd expect that changes made while autocommit was 0 (e.g. the update) would not be committed without an explicit commit transaction statement. Not sure though!On Dec 9, 2019 02:46, Ewan Chou <notifications@github.com> wrote:This happens occasionally since TiDB update the transaction model to support large transaction.
I think this issue may not only affects TiDB.
After this log, the total becomes wrong.
2019-12-06 23:01:26,854{GMT}	INFO	[jepsen worker 3-n4] jepsen.util: 3	:info	:transfer	{:from 3, :to 7, :amount 1}	:timed-out

The corresponding tidb log is the following:
[user=root@172.18.0.4] [schemaVersion=30] [txnStartTS=0] [current_db=test] [sql="set autocommit=0"]
[2019/12/06 23:01:26.854 +00:00] [INFO] [session.go:2041] [GENERAL_LOG] [conn=2] [user=root@172.18.0.4] [schemaVersion=30] [txnStartTS=0] [current_db=test] [sql="select balance from accounts3 FOR UPDATE"]
[2019/12/06 23:01:26.855 +00:00] [INFO] [2pc.go:1042] ["2PC clean up done"] [conn=2] [txnStartTS=413053298079170561]
[2019/12/06 23:01:26.856 +00:00] [INFO] [session.go:2041] [GENERAL_LOG] [conn=2] [user=root@172.18.0.4] [schemaVersion=30] [txnStartTS=413053298105384965] [current_db=test] [sql="select balance from accounts7 FOR UPDATE"]
[2019/12/06 23:01:26.857 +00:00] [INFO] [session.go:2041] [GENERAL_LOG] [conn=2] [user=root@172.18.0.4] [schemaVersion=30] [txnStartTS=413053298105384965] [current_db=test] [sql="update accounts3 set balance = balance - 1 where id = 0"]
[2019/12/06 23:01:26.858 +00:00] [INFO] [session.go:2041] [GENERAL_LOG] [conn=2] [user=root@172.18.0.4] [schemaVersion=30] [txnStartTS=413053298105384965] [current_db=test] [sql="set autocommit=1"]
[2019/12/06 23:01:26.862 +00:00] [INFO] [server.go:425] ["connection closed"] [conn=2]

The log shows that a transfer only updated one account, then executed set autocommit=1 before close, then the unfinished transaction is committed.
Could this be a bug in jdbc?
One of my suspicions is:
https://github.com/clojure/java.jdbc/blob/master/src/main/clojure/clojure/java/jdbc.clj#L829
set autocommit = 1 is executed in the finally block which means if the rollback failed to execute, then set autocommit = 1 is still being executed.

**Comment by coocood** [comment]
I mean TiDB is committing the transaction implicitly because the value of autocommit changed.

The behavior is the same as MySQL, tested on MySQL 8.0.12.

**Comment by coocood** [comment]
https://dev.mysql.com/doc/refman/8.0/en/implicit-commit.html

`SET autocommit = 1 (if the value is not already 1)` is listed.

**Comment by aphyr** [comment]
Oh! Yeah, that does seem unambiguous then! Want to open a bug on clojure.jdbc?On Dec 9, 2019 07:04, Ewan Chou <notifications@github.com> wrote:https://dev.mysql.com/doc/refman/8.0/en/implicit-commit.html
SET autocommit = 1 (if the value is not already 1) is listed.

**Comment by coocood** [comment]
Opened https://github.com/seancorfield/next-jdbc/issues/80

**Comment by aphyr** [comment]
You know, one odd thing about this is that the code appears to call .rollback prior to resetting autocommit... So... Why aren't we seeing a rollback in the server logs? Is it possible that... Maybe there wasn't an exception thrown? Maybe the test error handling code swallowed the exception before the transaction handler got a chance to realize a problem occurred?On Dec 9, 2019 07:28, Ewan Chou <notifications@github.com> wrote:Opened seancorfield/next-jdbc#80

**Comment by coocood** [comment]
Or maybe the `rollback` in the `catch` block itself failed, then `finally` code is executed.

**Comment by aphyr** [comment]
If that were the case, we should see a "Rollback failed handling ..." ex-info error...

**Comment by seancorfield** [comment]
The transaction will have been committed or rolled back before `java.jdbc` tries to reset the auto-commit status back to whatever it was before the transaction was started.

If any DB operation inside the transaction throws an exception, that code attempts to rollback first, then restores the auto-commit status.

If all DB operations inside the transaction complete, it either rolls back or commits (based on the rollback only setting), and then restores the auto-commit status.

_If the attempt to rollback (after a DB operation exception) fails, the code would restore the auto-commit status -- which could commit the data -- but you should get the combined exception._

Given that `SET autocommit = 1` will only occur if the original connection _was already set to autocommit_ prior to the transaction, I'm not sure what `java.jdbc` should do if the rollback fails? Should it leave the connection in a state different from how it found it? Even if it leaves it in that different state, if the rollback has failed, you're still going to get a partial transaction committed if you do anything else on that connection I think, yes?

**Comment by coocood** [comment]
@seancorfield 
In this case, the thread executes the transaction is killed, and the connection is closed right after it executes `set autocommit = 1`.

Maybe it is better If we move `set autocommit = 1` into the try and catch block rather than `finally` block.

**Comment by seancorfield** [comment]
Ah, yes, so there would be _two_ calls to restore the auto-commit, both on the "happy path". Yeah, that sounds reasonable. I'll definitely fix it for `next.jdbc` then. How likely am I to persuade you to migrate from `clojure.java.jdbc` to `next.jdbc` if it includes that fix? :)

**Comment by aphyr** [comment]
Popping in here--I haven't had a chance to look at this bug (except on my phone in bed), so I'm not sure whether this is Jepsen's fault or something in clojure.jdbc, but I can say that I'm open to moving future tests to next.jdbc. :-)

**Comment by coocood** [comment]
I just learn Clojure for a few days, I think it's a little hard for me to do the migration work right now.
Maybe later when I have more experience on Clojure code, I can try it.

**Comment by seancorfield** [comment]
That turned out to be a bit trickier to fix than it seemed above. Feedback on how I (attempted to) fix it welcome...

**Comment by coocood** [comment]
@seancorfield 
I'm not an expert of JAVA, but I just wondering is it possible that the line set `restore-ac = true` didn't have a chance to run, but go to the finally code directly?

**Comment by seancorfield** [comment]
@coocood That line will be executed if any of the following happen:

* The underlying SQL operation throws an exception
* The transaction is rollback-only and the SQL operation succeeds but the rollback throws an exception (in which case `restore-ac?` will already be `false`)
* The transaction is not rollback-only and the SQL operation succeeds but the commit throws an exception

That line will not be executed if:

* The transaction is rollback-only and the SQL operation succeeds and the rollback also succeeds (and `restore-ac?` will be `true` by that point)
* The transaction is not rollback-only and the SQL operation succeeds and the commit also succeeds (and `restore-ac?` will not have been changed from its initial `true` value)

So I think the answer to your question is "no" if I'm understanding your question correctly.

**Comment by coocood** [comment]
@seancorfield 
Thank you, I've no question about the fix now.
I'll try `next.jdbc` later.

**Comment by coocood** [comment]
@seancorfield 
I have spent a full day trying to migrate to `next.jdbc` but failed.
I plan to fix the bug in a forked `clojure.java.jdbc`.

**Comment by seancorfield** [comment]
@coocood OK, in that case I'll fix it in `java.jdbc` as well -- see https://clojure.atlassian.net/browse/JDBC-179

**Comment by seancorfield** [comment]
@coocood `org.clojure/java.jdbc` 0.7.11 is available on Maven Central with this fix. Let me know how it goes.

**Comment by coocood** [comment]
@seancorfield 
Thank you!
I have updated to 0.7.11 in our CI branch, no problem so far.
