### ISSUE TITLE
How to download and run binary file to be tested?

### ISSUE THREAD

**Issue by zackteo** [jepsen-io/jepsen#503]
Hello Kyle, am not too sure if I should be asking questions here but have followed and finished the jepsen tutorial. Am trying to use jepsen to test my own distributed system (kademlia implementation) for a uni project.

However I'm not sure how I might want to modify the code below to install my binary file instead. My distributed system implementation (a variant of kademelia) is a golang project which I can turn into a binary with `go build` but am not sure where to host it to follow this same format (have tried mediafire and google drive). Or adapt the code to download and run the binary. 
```clj
(c/su
        (let [url (str "https://storage.googleapis.com/etcd/" version
                       "/etcd-" version "-linux-amd64.tar.gz")]
          (cu/install-archive! url dir))
```
Any help would be greatly appreciated! >< (Also any tips to make the development process more Clojure REPL driven?)

**Comment by aphyr** [comment]
Hi Zachary. You can host files on any web server you want. `install-archive!` is specifically for tarballs and zip files. If you just want to download a single file, I'd suggest using `jepsen.control/exec` with `curl` or `wget`. If you want to deploy it from your control node directly, rather than downloading from the web, see `jepsen.control/upload`.

For the REPL, sure, you can run `lein repl` in a Jepsen project, just like any Clojure program. Your entry point will probably be `jepsen.core/run!`. In practice, I tend not to use the REPL much in Jepsen work--there's often so much interlocking state that re-typing things in the REPL or evaluating editor forms takes longer than just running the CLI command again.

**Comment by zackteo** [comment]
Thank you for responding so promptly :) I ended up getting something working with `jepsen.control/upload`.
```clj
(c/exec :mkdir :-p dir)
(c/upload "resources/kademlia" (str dir "/" binary))
(c/exec :chmod :+x (str dir "/" binary))
```
Though it took me quite a bit of finicking to realise that the binary I produced on my manjaro system was produced using too updated a version of `glibc` for the debian nodes to update to. Ended up creating the binary with the command node 😅 ...
```bash
apt-get install -y golang-go
go bulid
mv main ../kademlia.bookmarks/resources/kademlia
```
