### ISSUE TITLE
General question about long_fork test scope

### ISSUE THREAD

**Issue by zhangysh1995** [jepsen-io/jepsen#507]
Hi, I have a very general question about the usage scope of this test. My question may be a bit weird but I am very curious about this point.

As said in the comments, this test can identify conflicting timestamp orders inferred from the transaction histories.  There is an example:

````
      key   r1    r2    r3    r4

      x     0     1 --- 1 --- 1

      y     0     1 --- 1     0

      z     0 --- 0     2     1

````

If we have these connections, can I also say that this history is serializable? Because we have the order of transactions as: `r1 < r2 < r3 < r4`.

Can I say that if this test says there is an order of the transactions, then there is no violation for both snapshot isolation and Serializability? 

Thank you very much!

**Comment by aphyr** [comment]
I don't think this history is serializable, no: y flips from 0 to 1 and back to 0 again. It's been years since I wrote this example and I can't tell (in the few minutes I have before leaving for the vet's office) whether this is a mistake on my part, or intended behavior that catches long-fork but allows nonserializable histories.

If you're trying to verify serializability or snapshot isolation in general, this is the wrong test: you want Elle. In general, I'd prefer Elle to long-fork: it finds everything long-fork can, but more efficiently, more generally, and with better visualization.
