### ISSUE TITLE
empty-transaction-graph assertion

### ISSUE THREAD

**Issue by yito88** [jepsen-io/jepsen#511]
I tried Elle with `independent` concurrent-generator.
However, it failed due to `:empty-transaction-graph`.
Can a test ignore this assertion?
```
 {:stats
   {:valid? false,
    :count 2,
    :ok-count 0,
    :fail-count 2,
    :info-count 0,
    :by-f
    {:txn
     {:valid? false,
      :count 2,
      :ok-count 0,
      :fail-count 2,
      :info-count 0}}},
   :exceptions {:valid? true},
   :workload
   {:valid? :unknown,
    :anomaly-types (:empty-transaction-graph),
    :anomalies {:empty-transaction-graph true},
    :not #{},
    :also-not #{}},
   :valid? false},
```

**Comment by aphyr** [comment]
Sure, you can ignore this, but it's a sign that your test is broken--its not going to tell you anything.On Jul 24, 2021 23:25, Yuji Ito ***@***.***> wrote:
I tried Elle with independent concurrent-generator.
However, it failed due to :empty-transaction-graph.
Can a test ignore this assertion?
 {:stats
   {:valid? false,
    :count 2,
    :ok-count 0,
    :fail-count 2,
    :info-count 0,
    :by-f
    {:txn
     {:valid? false,
      :count 2,
      :ok-count 0,
      :fail-count 2,
      :info-count 0}}},
   :exceptions {:valid? true},
   :workload
   {:valid? :unknown,
    :anomaly-types (:empty-transaction-graph),
    :anomalies {:empty-transaction-graph true},
    :not #{},
    :also-not #{}},
   :valid? false},

**Comment by yito88** [comment]
Thank you for your reply.
I'm wondering how to invalid the assertion.
This case is expected. It often happens if the test time almost ends while a new sequence starts.

**Comment by aphyr** [comment]
Oh! Yeah, you'll want to write a little wrapper Checker then--you could either ignore the fault when it comes out of Elle, or not bother checking short histories. I would still suggest that you try to detect and alert on this behavior in aggregate, because it's easy to wind up with a test that doesn't actually check anything--this is a safety indicator to help prevent that. :)

**Comment by yito88** [comment]
Sorry for the late reply, and thank you for the suggestion.
I've added a wrapped checker to avoid this alert.
Thanks!
