### ISSUE TITLE
jepsen 0.2.7-sn  AgentProxyException: connector is not available

### ISSUE THREAD

**Issue by eskuai** [jepsen-io/jepsen#547]
If I run test using  [jepsen "0.2.7-SNAPSHOT"]

i got
```
Caused by: com.jcraft.jsch.agentproxy.AgentProxyException: connector is not available:
        at com.jcraft.jsch.agentproxy.ConnectorFactory.createConnector(ConnectorFactory.java:120)
        at jepsen.control.sshj$agent_proxy.invokeStatic(sshj.clj:38)
        at jepsen.control.sshj$agent_proxy.invoke(sshj.clj:36)
        at jepsen.control.sshj$auth_BANG_$fn__6739.invoke(sshj.clj:54)
        at jepsen.control.sshj$auth_BANG_.invokeStatic(sshj.clj:53)
        at jepsen.control.sshj$auth_BANG_.invoke(sshj.clj:42)
        at jepsen.control.sshj.SSHJRemote.connect(sshj.clj:118)
```

When using   [jepsen "0.2.1-SNAPSHOT"]

```
         "jepsen.checker$unbridled_optimism$reify__8609@470c4229"]
 :argv ("test" "-n" "n1" "n2" "n3")
 :nemesis
 #object[jepsen.nemesis$reify__9186
         "0x6408be5"
         "jepsen.nemesis$reify__9186@6408be5"]
 :active-histories
 #object[clojure.lang.Atom "0x549d14fe" {:status :ready, :val #{}}]
 :nodes ["n1"]
 :test-count 1
 :generator nil
 :os
 #object[jepsen.os.centos.CentOS
         "0x2e44cb34"
         "jepsen.os.centos.CentOS@2e44cb34"]
 :time-limit 60}

INFO [2022-08-10 12:02:28,155] jepsen node n1 - jepsen.os.centos n1 setting up centos
INFO [2022-08-10 12:02:30,013] jepsen node n1 - jepsen.util #{"iproute"
  "curl"
  "gcc-c++"
  "logrotate"
  "gcc"
  "rsyslog"
  "unzip"
  "vim-common"
  "wget"
  "ncurses-devel"}
```

it works ok...

any clues?

**Comment by qvad** [comment]
@eskuai you now need to specify `--ssh-private-key ~/.ssh/id_rsa` argument while launching `lein`
if you search previous output you will probably notice something like that:
```
 :ssh
 {:dummy? false,
  :username "root",
  :password "root",
  :strict-host-key-checking false,
  :private-key-path nil}
```
while in previous versions there was default `private-key-path=~/.ssh/id_rsa` mapping, haven't discovered in the code why it's missed now. 

@aphyr it looks like an issue in 0.2.7+ versions. Workaround is defining `~/.ssh/id_rsa` key path explicitly via `--ssh-private-key` arg.

**Comment by markbradley27** [comment]
I think the issue lies here ([0.2.7 switched to using sshj by default](https://github.com/jepsen-io/jepsen/releases/tag/v0.2.7) instead of clj-ssh, which is probably why you aren't having issues with the older versions): https://github.com/jepsen-io/jepsen/blob/v0.3.5/jepsen/src/jepsen/control/sshj.clj#L62

That `auth!` method tries a few authentication approaches:
1. User-provided key
2. ssh-agent
3. auto-detected keys
4. username/password

However it looks like the step that tries the ssh-agent only catches in the case where an agent was found but unable to connect. If an agent isn't found at all, that exception isn't caught and it never goes on to try approaches 3 and 4 (3 is probably what you were hoping for).

Submitted #591 to address this.
